### ISSUE TITLE
pip-compile error

### ISSUE THREAD

**Issue by nikolay** [nvie/pip-tools#122]
```
$ pip-compile requirements.in
Traceback (most recent call last):
  File "~/pyenv/versions/test/bin/pip-compile", line 9, in <module>
    load_entry_point('pip-tools==1.0', 'console_scripts', 'pip-compile')()
  File "~/pyenv/versions/test/lib/python3.4/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "~/pyenv/versions/test/lib/python3.4/site-packages/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "~/pyenv/versions/test/lib/python3.4/site-packages/pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "~/pyenv/versions/test/lib/python3.4/site-packages/piptools/scripts/compile.py", line 13, in <module>
    from piptools.package_manager import PackageManager
  File "~/pyenv/versions/test/lib/python3.4/site-packages/piptools/package_manager.py", line 21, in <module>
    from pip.download import get_file_content, unpack_vcs_link, PipSession
ImportError: cannot import name 'PipSession'
```

**Comment by blueyed** [comment]
Which pip version are you using?

**Comment by nikolay** [comment]
@blueyed That error was with version 1.4.1 install with Python 3.4. When I did `pip install -U pip`, it got upgraded to v6.0.6 and the error now is:

```
$ pip-compile
Traceback (most recent call last):
  File "~/pyenv/versions/test/bin/pip-compile", line 9, in <module>
    load_entry_point('pip-tools==1.0', 'console_scripts', 'pip-compile')()
  File "~/pyenv/versions/test/lib/python3.4/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "~/pyenv/versions/test/lib/python3.4/site-packages/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "~/pyenv/versions/test/lib/python3.4/site-packages/pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "~/pyenv/versions/test/lib/python3.4/site-packages/piptools/scripts/compile.py", line 13, in <module>
    from piptools.package_manager import PackageManager
  File "~/pyenv/versions/test/lib/python3.4/site-packages/piptools/package_manager.py", line 22, in <module>
    from pip.index import Link, PackageFinder, package_to_requirement
ImportError: cannot import name 'package_to_requirement'
```

**Comment by blueyed** [comment]
That would be https://github.com/nvie/pip-tools/issues/124 then.
