### ISSUE TITLE
ImportError: cannot import name package_to_requirement

### ISSUE THREAD

**Issue by blueyed** [nvie/pip-tools#124]
pip has removed `package_to_requirement` (in https://github.com/pypa/pip/commit/958e6bc).

pip-compile fails as follows:

    Traceback (most recent call last):
      File "/path/to/pyenv/project/bin/pip-compile", line 9, in <module>
        load_entry_point('pip-tools==1.0', 'console_scripts', 'pip-compile')()
      File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 356, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2472, in load_entry_point
        self.check_version_conflict()
      File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2186, in load
        except ValueError:
      File "…/pip-tools/piptools/scripts/compile.py", line 13, in <module>
        from piptools.package_manager import PackageManager
      File "…/pip-tools/piptools/package_manager.py", line 22, in <module>
        from pip.index import Link, PackageFinder, package_to_requirement
    ImportError: cannot import name package_to_requirement

**Comment by blueyed** [comment]
I guess we should vendorize/import `package_to_requirement` then?
Where should it go?

**Comment by antonagestam** [comment]
Quick workaround for people looking for a solution is to install pip 1.5.6:
```
$ pip install pip==1.5.6
```

**Comment by blueyed** [comment]
I'd recommend to try https://github.com/nvie/pip-tools/pull/126 instead.

@nvie 
Reviewing (and hopefully merging) it would be appreciated!
