### ISSUE TITLE
[future] cannot compile Sphinx: RuntimeError: Spec set was not resolved after 12 rounds. This is likely a bug.

### ISSUE THREAD

**Issue by blueyed** [nvie/pip-tools#138]
Sphinx cannot be compiled/resolved.

I am attaching only the log for the first 3 rounds, with the exception at the end.

    % pip-compile --verbose test-sphinx.in

    ===> Collecting source requirements
    Sphinx (from test-sphinx.in:1)

    ===> Normalizing source requirements
    sphinx (from test-sphinx.in:1)

    ===> Resolving full tree
    - Finding best package matching ['sphinx']
      Found best match: 1.3.1 (from PyPI)
    - Getting dependencies for sphinx-1.3.1
      Found: ['six>=1.4', 'Jinja2>=2.3', 'Pygments>=2.0', 'docutils>=0.11', 'snowballstemmer>=1.1', 'babel>=1.3', 'alabaster>=0.7,<0.8', 'sphinx-rtd-theme>=0.1,<0.2'] (from dependency cache)
    After round #1:
      - Jinja2>=2.3 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - Pygments>=2.0 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - alabaster<0.8,>=0.7 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - babel>=1.3 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - docutils>=0.11 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - six>=1.4 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - snowballstemmer>=1.1 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - sphinx (from test-sphinx.in:1)
      - sphinx-rtd-theme<0.2,>=0.1 (from test-sphinx.in:1 ~> sphinx==1.3.1)
    - Finding best package matching ['alabaster<0.8,>=0.7']
      Found best match: 0.7.2 (from PyPI)
    - Getting dependencies for alabaster-0.7.2
      Found: [] (from dependency cache)
    - Finding best package matching ['babel>=1.3']
      Found best match: 1.3 (from PyPI)
    - Getting dependencies for babel-1.3
      Found: ['pytz>=0a'] (from dependency cache)
    - Finding best package matching ['docutils>=0.11']
      Found best match: 0.12 (from PyPI)
    - Getting dependencies for docutils-0.12
      Found: [] (from dependency cache)
    - Finding best package matching ['jinja2>=2.3']
      Found best match: 2.7.3 (from PyPI)
    - Getting dependencies for jinja2-2.7.3
      Found: ['markupsafe'] (from dependency cache)
    - Finding best package matching ['pygments>=2.0']
      Found best match: 2.0.2 (from PyPI)
    - Getting dependencies for pygments-2.0.2
      Found: [] (from dependency cache)
    - Finding best package matching ['six>=1.4']
      Found best match: 1.9.0 (from PyPI)
    - Getting dependencies for six-1.9.0
      Found: [] (from dependency cache)
    - Finding best package matching ['snowballstemmer>=1.1']
      Found best match: 1.2.0 (from PyPI)
    - Getting dependencies for snowballstemmer-1.2.0
      Found: [] (from dependency cache)
    - Finding best package matching ['sphinx']
      Found best match: 1.3.1 (from link cache)
    - Finding best package matching ['sphinx-rtd-theme<0.2,>=0.1']
      Found best match: 0.1.7 (from PyPI)
    - Getting dependencies for sphinx-rtd-theme-0.1.7
      Found: ['sphinx>=1.1'] (from dependency cache)
    After round #2:
      - Jinja2>=2.3 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - Pygments>=2.0 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - alabaster<0.8,>=0.7 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - babel>=1.3 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - docutils>=0.11 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - markupsafe (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> jinja2==2.7.3)
      - pytz>=0a (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> babel==1.3)
      - six>=1.4 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - snowballstemmer>=1.1 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - sphinx (from test-sphinx.in:1)
      - sphinx-rtd-theme<0.2,>=0.1 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - sphinx>=1.1 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7)
    - Finding best package matching ['alabaster<0.8,>=0.7']
      Found best match: 0.7.2 (from link cache)
    - Finding best package matching ['babel>=1.3']
      Found best match: 1.3 (from link cache)
    - Finding best package matching ['docutils>=0.11']
      Found best match: 0.12 (from link cache)
    - Finding best package matching ['jinja2>=2.3']
      Found best match: 2.7.3 (from link cache)
    - Finding best package matching ['markupsafe']
      Found best match: 0.23 (from PyPI)
    - Getting dependencies for markupsafe-0.23
      Found: [] (from dependency cache)
    - Finding best package matching ['pygments>=2.0']
      Found best match: 2.0.2 (from link cache)
    - Finding best package matching ['pytz>=0a']
      Found best match: 2014.10 (from PyPI)
    - Getting dependencies for pytz-2014.10
      Found: [] (from dependency cache)
    - Finding best package matching ['six>=1.4']
      Found best match: 1.9.0 (from link cache)
    - Finding best package matching ['snowballstemmer>=1.1']
      Found best match: 1.2.0 (from link cache)
    - Finding best package matching ['sphinx>=1.1']
      Found best match: 1.3.1 (from PyPI)
    - Finding best package matching ['sphinx-rtd-theme<0.2,>=0.1']
      Found best match: 0.1.7 (from link cache)
    After round #3:
      - Jinja2>=2.3 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7 ~> sphinx==1.3.1)
      - Jinja2>=2.3 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - Pygments>=2.0 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7 ~> sphinx==1.3.1)
      - Pygments>=2.0 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - alabaster<0.8,>=0.7 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7 ~> sphinx==1.3.1)
      - alabaster<0.8,>=0.7 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - babel>=1.3 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7 ~> sphinx==1.3.1)
      - babel>=1.3 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - docutils>=0.11 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7 ~> sphinx==1.3.1)
      - docutils>=0.11 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - markupsafe (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> jinja2==2.7.3)
      - pytz>=0a (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> babel==1.3)
      - six>=1.4 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7 ~> sphinx==1.3.1)
      - six>=1.4 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - snowballstemmer>=1.1 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7 ~> sphinx==1.3.1)
      - snowballstemmer>=1.1 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - sphinx (from test-sphinx.in:1)
      - sphinx-rtd-theme<0.2,>=0.1 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7 ~> sphinx==1.3.1)
      - sphinx-rtd-theme<0.2,>=0.1 (from test-sphinx.in:1 ~> sphinx==1.3.1)
      - sphinx>=1.1 (from test-sphinx.in:1 ~> sphinx==1.3.1 ~> sphinx-rtd-theme==0.1.7)
    - Finding best package matching ['alabaster<0.8,>=0.7']
      Found best match: 0.7.2 (from link cache)
    - Finding best package matching ['babel>=1.3']
      Found best match: 1.3 (from link cache)
    - Finding best package matching ['docutils>=0.11']
      Found best match: 0.12 (from link cache)
    - Finding best package matching ['jinja2>=2.3']
      Found best match: 2.7.3 (from link cache)
    - Finding best package matching ['markupsafe']
      Found best match: 0.23 (from link cache)
    - Finding best package matching ['pygments>=2.0']
      Found best match: 2.0.2 (from link cache)
    - Finding best package matching ['pytz>=0a']
      Found best match: 2014.10 (from link cache)
    - Finding best package matching ['six>=1.4']
      Found best match: 1.9.0 (from link cache)
    - Finding best package matching ['snowballstemmer>=1.1']
      Found best match: 1.2.0 (from link cache)
    - Finding best package matching ['sphinx>=1.1']
      Found best match: 1.3.1 (from link cache)
    - Finding best package matching ['sphinx-rtd-theme<0.2,>=0.1']
      Found best match: 0.1.7 (from link cache)

      [...]

    Traceback (most recent call last):
      File "/home/daniel/Vcs/pip-tools/build/venv3/bin/pip-compile", line 9, in <module>
        load_entry_point('pip-tools==1.0', 'console_scripts', 'pip-compile')()
      File "/home/daniel/Vcs/pip-tools/build/venv3/lib/python3.4/site-packages/click/core.py", line 610, in __call__
        return self.main(*args, **kwargs)
      File "/home/daniel/Vcs/pip-tools/build/venv3/lib/python3.4/site-packages/click/core.py", line 590, in main
        rv = self.invoke(ctx)
      File "/home/daniel/Vcs/pip-tools/build/venv3/lib/python3.4/site-packages/click/core.py", line 782, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/daniel/Vcs/pip-tools/build/venv3/lib/python3.4/site-packages/click/core.py", line 416, in invoke
        return callback(*args, **kwargs)
      File "/home/daniel/Vcs/pip-tools/piptools/scripts/compile.py", line 186, in cli
        compile_specs(src_files, include_sources=include_sources, dry_run=dry_run)
      File "/home/daniel/Vcs/pip-tools/piptools/scripts/compile.py", line 118, in compile_specs
        pinned_spec_set = resolver.resolve()
      File "/home/daniel/Vcs/pip-tools/piptools/resolver.py", line 42, in resolve
        'This is likely a bug.' % max_rounds)
    RuntimeError: Spec set was not resolved after 12 rounds. This is likely a bug.

**Comment by blueyed** [comment]
This is fixed by now.
