### ISSUE TITLE
Limit pickle protocol for cache to be compatible with Python 2/3

### ISSUE THREAD

**Issue by blueyed** [nvie/pip-tools#149]
When running the cram tests with Python 3 and then Python 2, I've seen
the following error.

This will probably also happen when using pip-tools with both Python 2 and Python 3 simultaneously.

A fix would be to limit the pickle protocol to version 2, or use different caches for Python 2 and Python 3.

Maybe `pickle.HIGHEST_PROTOCOL` could be used explicitly (via `protocol=`) and in the file name?

This would use protocol version 4 with 3.4.

But then again it might be better to share the same cache across Python 2 and 3 instead, and there is probably no real benefit from newer protocols for pip-tool's use case, so I suggest using protocol=2.

    Traceback (most recent call last):

    File "FOO/bin/pip-compile", line 9, in <module>
      load_entry_point('pip-tools==1.0', 'console_scripts', 'pip-compile')()
    File "/tmp/cramtests-pSbh22/pip-compile.t/FOO/lib/python2.7/site-packages/click/core.py", line 664, in __call__
      return self.main(*args, **kwargs)
    File "/tmp/cramtests-pSbh22/pip-compile.t/FOO/lib/python2.7/site-packages/click/core.py", line 644, in main
      rv = self.invoke(ctx)
    File "/tmp/cramtests-pSbh22/pip-compile.t/FOO/lib/python2.7/site-packages/click/core.py", line 837, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/tmp/cramtests-pSbh22/pip-compile.t/FOO/lib/python2.7/site-packages/click/core.py", line 464, in invoke
      return callback(*args, **kwargs)
    File "…/pip-tools/piptools/scripts/compile.py", line 185, in cli
      compile_specs(src_files, include_sources=include_sources, dry_run=dry_run)
    File "…/pip-tools/piptools/scripts/compile.py", line 117, in compile_specs
      pinned_spec_set = resolver.resolve()
    File "…/pip-tools/piptools/resolver.py", line 44, in resolve
      if not self.resolve_one_round():
    File "…/pip-tools/piptools/resolver.py", line 28, in resolve_one_round
      new_deps = self.find_new_dependencies()
    File "…/pip-tools/piptools/resolver.py", line 91, in find_new_dependencies
      all_deps = self.find_all_dependencies()
    File "…/pip-tools/piptools/resolver.py", line 73, in find_all_dependencies
      version = pkgmgr.find_best_match(spec)
    File "…/pip-tools/piptools/package_manager.py", line 288, in find_best_match
      version, source = _find_cached_match(spec)
    File "…/pip-tools/piptools/package_manager.py", line 232, in _find_cached_match
      if (name, version) in self._dep_cache:
    File "…/pip-tools/piptools/cache.py", line 39, in __contains__
      return item in self.cache
    File "…/pip-tools/piptools/cache.py", line 19, in cache
      self.read_cache()
    File "…/pip-tools/piptools/cache.py", line 26, in read_cache
      self._cache = pickle.load(f)
    File "…/pyenv/2.7.9/lib/python2.7/pickle.py", line 1378, in load
      return Unpickler(file).load()
    File "…/pyenv/2.7.9/lib/python2.7/pickle.py", line 858, in load
      dispatch[key](self)
    File "…/pyenv/2.7.9/lib/python2.7/pickle.py", line 886, in load_proto
      raise ValueError, "unsupported pickle protocol: %d" % proto
  ValueError: unsupported pickle protocol: 3

**Comment by blueyed** [comment]
Fixed via #153.
