### ISSUE TITLE
future: AttributeError: 'NoneType' object has no attribute 'key' with git requirement

### ISSUE THREAD

**Issue by blueyed** [nvie/pip-tools#156]
Using the following in a requirements file will produce a AttributeError (instead of the not-supported error):

    % echo "git+https://github.com/mverteuil/pytest-ipdb.git" > test.in
    % pip-compile test.in

    Traceback (most recent call last):
      File "/home/daniel/.pyenv/versions/tmm3/bin/pip-compile", line 9, in <module>
        load_entry_point('pip-tools==1.0.dev1', 'console_scripts', 'pip-compile')()
      File "/home/daniel/.pyenv/versions/tmm3/lib/python3.4/site-packages/click/core.py", line 664, in __call__
        return self.main(*args, **kwargs)
      File "/home/daniel/.pyenv/versions/tmm3/lib/python3.4/site-packages/click/core.py", line 644, in main
        rv = self.invoke(ctx)
      File "/home/daniel/.pyenv/versions/tmm3/lib/python3.4/site-packages/click/core.py", line 837, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/daniel/.pyenv/versions/tmm3/lib/python3.4/site-packages/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "/home/daniel/Vcs/pip-tools/piptools/scripts/compile.py", line 81, in cli
        results = resolver.resolve()
      File "/home/daniel/Vcs/pip-tools/piptools/resolver.py", line 58, in resolve
        self._check_constraints()
      File "/home/daniel/Vcs/pip-tools/piptools/resolver.py", line 89, in _check_constraints
        for constraint in self.constraints:
      File "/home/daniel/Vcs/pip-tools/piptools/resolver.py", line 42, in constraints
        self.their_constraints)))
      File "/home/daniel/Vcs/pip-tools/piptools/resolver.py", line 115, in _group_constraints
        for _, ireqs in full_groupby(constraints, key=lambda ireq: ireq.req.key):
      File "/home/daniel/Vcs/pip-tools/piptools/utils.py", line 79, in full_groupby
        return groupby(sorted(iterable, key=key), key=key)
      File "/home/daniel/Vcs/pip-tools/piptools/resolver.py", line 115, in <lambda>
        for _, ireqs in full_groupby(constraints, key=lambda ireq: ireq.req.key):
    AttributeError: 'NoneType' object has no attribute 'key'

    ![x for x in constraints if x.req is None]
    [<InstallRequirement object: git+https://github.com/mverteuil/pytest-ipdb.git (from -r requirements/testing.in (line 21)) editable=False>]

**Comment by nvie** [comment]
Thanks for finding this bug. It's now fixed.
