### ISSUE TITLE
pip-compile fails when enum34 is listed in requirements.in

### ISSUE THREAD

**Issue by veegee** [nvie/pip-tools#228]
This error occurs when `pip-compile` is run with Python 3.5.

```
➜ pip-compile requirements.pypy.in
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/piptools/scripts/compile.py", line 111, in cli
    results = resolver.resolve()
  File "/usr/local/lib/python3.5/site-packages/piptools/resolver.py", line 78, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.5/site-packages/piptools/resolver.py", line 162, in _resolve_one_round
    for best_match in best_matches
  File "/usr/local/lib/python3.5/site-packages/piptools/resolver.py", line 163, in <genexpr>
    for dep in self._iter_dependencies(best_match))
  File "/usr/local/lib/python3.5/site-packages/piptools/resolver.py", line 234, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 128, in get_dependencies
    dependencies = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 505, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 123, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 410, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.5/site-packages/pip/utils/__init__.py", line 733, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/7j/2txnr59s19n54jpb0g5mcjwh0000gn/T/tmpw4n1q_p7build/enum34
```

It works when `pip-compile` is run with Python 2.7.

**Comment by nvie** [comment]
I don't know what is causing this. Apparently `python setup.py egg_info` fails when executed on this package. Can you run that manually and see if there's perhaps more output? Any help here is appreciated!

**Comment by nvie** [comment]
I'm making #343 the main issue for tracking this.
