### ISSUE TITLE
pip-sync fails to uninstall if find-links are set

### ISSUE THREAD

**Issue by chaoflow** [nvie/pip-tools#298]
```

Usage:   
  pip uninstall [options] <package> ...
  pip uninstall [options] -r <requirements file> ...

no such option: -f
Traceback (most recent call last):
  File "/tmp/foo/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/tmp/foo/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/foo/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/tmp/foo/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/foo/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/tmp/foo/local/lib/python2.7/site-packages/piptools/scripts/sync.py", line 75, in cli
    pip_flags=pip_flags))
  File "/tmp/foo/local/lib/python2.7/site-packages/piptools/sync.py", line 137, in sync
    check_call(['pip', 'uninstall', '-y'] + pip_flags + sorted(to_uninstall))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'uninstall', '-y', u'-f', u'https://ternaris.com/pypi', 'bagbunker', 'marv']' returned non-zero exit status 2
```

**Comment by chaoflow** [comment]
Sorry, I'm aiming to remember not to mention an issue until I know the commit works and the commit message is correct.
