### ISSUE TITLE
pip-sync fails on empty virtualenv: Cannot uninstall requirement ansible, not installed

### ISSUE THREAD

**Issue by breerly** [nvie/pip-tools#340]
Trying to add pip-to our deps workflow, but getting this error on an empty virtualenv.

```
(env) yarpc/yarpc-python - [better-package-mgmt] » pip-sync
Cannot uninstall requirement ansible, not installed
Traceback (most recent call last):
  File "/usr/local/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/piptools/scripts/sync.py", line 75, in cli
    install_flags=install_flags))
  File "/usr/local/lib/python2.7/site-packages/piptools/sync.py", line 137, in sync
    check_call(['pip', 'uninstall', '-y'] + pip_flags + sorted(to_uninstall))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'uninstall', '-y', 'ansible', 'argparse', 'arrow', 'binaryornot', 'boto', 'chardet', 'clay-config-file', 'cookiecutter', 'docutils', 'future', 'gdal', 'greenlet', 'httpie', 'jedi', 'lxml', 'mercurial', 'msgpack-python', 'multi-key-dict', 'neovim', 'paramiko', 'pbr', 'pillow', 'py-look-for-timeouts', 'pyfiglet', 'pygal', 'pygaljs', 'pygments', 'pysocks', 'pytest-benchmark', 'python', 'python-dateutil', 'python-jenkins', 'pytz', 'pyyaml', 'rainbowstream', 'ruamel.base', 'ruamel.ordereddict', 'ruamel.yaml', 'sh', 'statistics', 'stevedore', 'trollius', 'twitter', 'vboxapi', 'virtualenv', 'virtualenv-clone', 'virtualenvwrapper', 'whichcraft', 'wsgiref', 'yarpc']' returned non-zero exit status 1
```

Any ideas?

**Comment by breerly** [comment]
Nevermind, looks like `pip-tools` should be installed *in* the virtualenv
