### ISSUE TITLE
pip-tools doesn't handle conflicts gracefully

### ISSUE THREAD

**Issue by LuisAlejandro** [nvie/pip-tools#346]
Test requirements.txt
```
reportlab==2.6
reportlab==3.1.44
```
Result:
```
$ pip-compile -v requirements.txt
Using indexes:
  https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:
  reportlab==2.6,==3.1.44

Finding the best candidates:
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/piptools/scripts/compile.py", line 163, in cli
    results = resolver.resolve()
  File "/usr/local/lib/python2.7/dist-packages/piptools/resolver.py", line 78, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/piptools/resolver.py", line 154, in _resolve_one_round
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/dist-packages/piptools/resolver.py", line 154, in <genexpr>
    best_matches = set(self.get_best_match(ireq) for ireq in constraints)
  File "/usr/local/lib/python2.7/dist-packages/piptools/resolver.py", line 201, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/usr/local/lib/python2.7/dist-packages/piptools/repositories/pypi.py", line 106, in find_best_match
    matching_candidates = [candidates_by_version[ver] for ver in matching_versions]
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/specifiers.py", line 200, in filter
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/specifiers.py", line 201, in filter
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/specifiers.py", line 151, in _coerce_version
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/version.py", line 41, in parse
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/version.py", line 210, in __init__
TypeError: expected string or buffer
```

**Comment by beedub** [comment]
do you mean that there should be a better error msg? though it's not directly saying there's a duplicate constraint, the issue is obvious from the error

**Comment by nvie** [comment]
The error message definitely needs to be improved, this is a low-level error that should be handled. That said, these requirements conflict and pip-tools will not be able to handle this.

**Comment by beedub** [comment]
I'm actually unable to reproduce this locally using latest `pip` (8.1.1) and latest `pip-tools`. @LuisAlejandro what's versions are you using?

**Comment by LuisAlejandro** [comment]
Yes, i mean `pip-tools` should die gracefully here. Although, personally i would like it to have an option to use the most recent version if there's a conflict like this, what do you think? I'm willing to make a PR with such a feature.
```
$ pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```
```
$ pip-compile --version
pip-compile, version 1.6.1
```

**Comment by LuisAlejandro** [comment]
Nevermind, this is a bug related to Debian.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=814397

After reinstalling pip from pypi, this is the output, which seems like a good one.

```
$ pip-compile -r -v text.txt 
Using indexes:
  https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:
  reportlab==2.6,==3.1.44

Finding the best candidates:
Could not find a version that matches reportlab==2.6,==3.1.44
Tried: 2.3, 2.3, 2.4, 2.5, 2.6, 2.7, 3.0, 3.1.8, 3.1.44, 3.2.0, 3.3.0
```

Thanks anyway.

**Comment by nvie** [comment]
I don't think picking either version is a good choice. pip-tools was born from the need to make these conflicts explicit in the first place. In a way, detecting these conflicts is it's job. The conflict itself should be addressed, pip-tools should not ignore it.
