### ISSUE TITLE
Issues with brotlipy

### ISSUE THREAD

**Issue by cancan101** [nvie/pip-tools#386]
Describe the issue briefly here.
##### Steps to replicate
1. Add `brotlipy` to requirements.in 
2. pip-compile
##### Expected result
- Created txt file
##### Actual result

```
Traceback (most recent call last):
  File "/Users/alex/.virtualenvs/venv/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/piptools/scripts/compile.py", line 195, in cli
    reverse_dependencies = resolver.reverse_dependencies(results)
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/piptools/resolver.py", line 267, in reverse_dependencies
    return self.dependency_cache.reverse_dependencies(non_editable)
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/piptools/cache.py", line 139, in reverse_dependencies
    return self._reverse_dependencies(ireqs_as_cache_values)
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/piptools/cache.py", line 163, in _reverse_dependencies
    for name, version_and_extras in cache_keys
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/piptools/utils.py", line 191, in lookup_table
    for value in values:
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/piptools/cache.py", line 164, in <genexpr>
    for dep_name in self.cache[name][version_and_extras])
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2986, in parse
    reqs = list(parse_requirements(s))
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2930, in parse_requirements
    "version spec")
  File "/Users/alex/.virtualenvs/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2906, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected ',' or end-of-list in enum34<2,>=1.0.4; python_version == "2.7" or python_version == "3.3" at ; python_version == "2.7" or python_version == "3.3"
```

**Comment by cancan101** [comment]
Closing as duplicate of: https://github.com/nvie/pip-tools/issues/379
