### ISSUE TITLE
pip-compile boto3 fail

### ISSUE THREAD

**Issue by mitbal** [nvie/pip-tools#426]
Pip-compile fail to generate requirements.txt from requirements.in if I input boto3 as one of the package to be installed.

##### Steps to replicate

1. create fresh new virtual environment `virtualenv venv` and activate it `source venv/bin/activate`
2. create new requirements.in file. In my example, I use this 4 libraries: flask, gensim, numpy, boto3
3. run pip-compile

##### Expected result

requirements.txt file is generated with boto3 version inside.

##### Actual result

It produce this error
`    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", u'futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7"', 'at', u'; python_version == "2.6" or python_version == "2.7"')`

Thanks in advance!

**Comment by davidovich** [comment]
I have tried to reproduce, without error. Here is my setup:

Windows 7
pip==9.0.1
pip-tools==1.8.0

**Comment by mitbal** [comment]
Thanks for the info, David. I myself run python 2.7.6 in Ubuntu 14.04 with the same version of pip and pip-tools.

I wonder if this is some kind of heisenbug because my colleague who first encountered this error, suddenly, somehow, managed to successfully install the package, without doing anything. However, I still run into this error.

I managed to install the package individually by running pip install in the terminal, but that kind of defeat the purpose of using pip-tools.

Here's the full traceback from my terminal. The error disappears if I remove boto3 from the requirements.in file, no matter the position (up, middle, or bottom).
```
Traceback (most recent call last):
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 223, in cli
    reverse_dependencies = resolver.reverse_dependencies(results)
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/piptools/resolver.py", line 273, in reverse_dependencies
    return self.dependency_cache.reverse_dependencies(non_editable)
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/piptools/cache.py", line 139, in reverse_dependencies
    return self._reverse_dependencies(ireqs_as_cache_values)
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/piptools/cache.py", line 163, in _reverse_dependencies
    for name, version_and_extras in cache_keys
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/piptools/utils.py", line 192, in lookup_table
    for value in values:
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/piptools/cache.py", line 164, in <genexpr>
    for dep_name in self.cache[name][version_and_extras])
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/pkg_resources.py", line 2625, in parse
    reqs = list(parse_requirements(s))
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/pkg_resources.py", line 2563, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/mitbal/workspace/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/pkg_resources.py", line 2541, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", u'futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7"', 'at', u'; python_version == "2.6" or python_version == "2.7"')
```

**Comment by davidovich** [comment]
@mitbal You might try to recreate your virtualenv, as it has *possibly* captured an older version of setuptools which fails to parse the [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers).

**Comment by mitbal** [comment]
Ah, the problem is gone and it works as intended after I updated setuptools using pip.
Thanks David!
