### ISSUE TITLE
Pip-sync fails but pip succeed

### ISSUE THREAD

**Issue by mitbal** [nvie/pip-tools#440]
Pip-sync fails to install libraries. Meanwhile, using `pip install -r requirements.txt` success with no error. 

##### Steps to replicate

1. Create fresh virtualenv `` and activate it ``
2. Upgrade pip and install pip-tools
3. Run `pip-sync requirements.txt`

My server runs Ubuntu 14.04

This is the content of the requirements.txt file:
```
boto3==1.4.3
boto==2.45.0              # via smart-open
botocore==1.4.91          # via boto3, s3transfer
bz2file==0.98             # via smart-open
click==6.6                # via flask
docutils==0.13.1          # via botocore
flask==0.11.1
futures==3.0.5            # via s3transfer
gensim==0.13.3
itsdangerous==0.24        # via flask
jinja2==2.8               # via flask
jmespath==0.9.0           # via boto3, botocore
markupsafe==0.23          # via jinja2
meld3==1.0.2              # via supervisor
numpy==1.11.3
python-dateutil==2.6.0    # via botocore
requests==2.12.4          # via smart-open
s3transfer==0.1.10        # via boto3
scipy==0.18.1             # via gensim
six==1.10.0               # via gensim, python-dateutil
smart-open==1.3.5         # via gensim
supervisor==3.3.1
werkzeug==0.11.11         # via flask
```

##### Expected result
All libraries installed.

##### Actual result
This error comes up:
```
 RuntimeError: Broken toolchain: cannot link a simple C program
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zNp8tS/gensim/
Traceback (most recent call last):
  File "/home/ubuntu/ml-application/word_vector_service/wvsenv/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/piptools/scripts/sync.py", line 72, in cli
    install_flags=install_flags))
  File "/home/ubuntu/ml-application/word_vector_service/wvsenv/local/lib/python2.7/site-packages/piptools/sync.py", line 157, in sync
    check_call([pip, 'install'] + pip_flags + install_flags + sorted(to_install))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', 'boto3==1.4.3', 'boto==2.45.0', 'botocore==1.4.91', 'bz2file==0.98', 'click==6.6', 'docutils==0.13.1', 'flask==0.11.1', 'futures==3.0.5', 'gensim==0.13.3', 'itsdangerous==0.24', 'jinja2==2.8', 'jmespath==0.9.0', 'markupsafe==0.23', 'meld3==1.0.2', 'numpy==1.11.3', 'python-dateutil==2.6.0', 'requests==2.12.4', 's3transfer==0.1.10', 'scipy==0.18.1', 'smart-open==1.3.5', 'supervisor==3.3.1', 'werkzeug==0.11.11']' returned non-zero exit status 1
```

Thanks in advance!

**Comment by mitbal** [comment]
Oops, turned out I just need to install gcc and python-dev. Problem solved.
